### ISSUE TITLE
Keep Getting The Module Not Found Error

### ISSUE THREAD

**Issue by D4ask** [D3ltaa/Bot-Codes#1]
even though i inserted the main file as Ticket-with-button-main/index.js in the package.json i still get the module not found error

**Comment by D3ltaa** [comment]
> even though i inserted the main file as Ticket-with-button-main/index.js in the package.json i still get the module not found error

Try to follow instructions  from read.md file in folder directory

**Comment by D4ask** [comment]
> > even though i inserted the main file as Ticket-with-button-main/index.js in the package.json i still get the module not found error
> 
> Try to follow instructions from read.md file in folder directory

i already done that and i still get the error no matter what

**Comment by D3ltaa** [comment]
> > > even though i inserted the main file as Ticket-with-button-main/index.js in the package.json i still get the module not found error
> > 
> > 
> > Try to follow instructions from read.md file in folder directory
> 
> i already done that and i still get the error no matter what

https://imgur.com/a/j96LPgV check the  way i done that here it work poperly

**Comment by D4ask** [comment]
> > > > even though i inserted the main file as Ticket-with-button-main/index.js in the package.json i still get the module not found error
> > > 
> > > 
> > > Try to follow instructions from read.md file in folder directory
> > 
> > 
> > i already done that and i still get the error no matter what
> 
> https://imgur.com/a/j96LPgV check the way i done that here it work poperly

oh thanks man it works now

**Comment by D4ask** [comment]
also im in ur discord server and i can say that your work is rlly incredible

**Comment by D3ltaa** [comment]
> also im in ur discord server and i can say that your work is rlly incredible

Im happy u fix the problem!!Im try my best ;)
